---
repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - pydocstyle>=5.1.1
          - flake8-absolute-import
          - flake8-black>=0.1.1
          - flake8-docstrings>=1.5.0
        language_version: python3
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v5.2.1
    hooks:
      - id: ansible-lint
        always_run: true
        additional_dependencies:
          - ansible-core
          - yamllint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
      - id: mypy
        # empty args needed in order to match mypy cli behavior
        args: []
        entry: mypy src/
        pass_filenames: false
        additional_dependencies:
          - molecule
          - molecule-docker
          - molecule-podman
          - packaging
  - repo: https://github.com/pycqa/pylint
    rev: v2.12.1
    hooks:
      - id: pylint
        additional_dependencies:
          - ansible-core
          - molecule
          - molecule-docker
          - molecule-podman
  - repo: https://github.com/PyCQA/doc8.git
    rev: 0.10.1
    hooks:
      - id: doc8
