name: tox

on:
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "main"
    tags-ignore:
      - "**"
  pull_request:
  schedule:
    - cron: 0 0 * * 0  # Run weekly

jobs:
  build:
    name: ${{ matrix.tox_env }}
    # ubuntu-latest is current older and we need last podman toolkit.
    # https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - tox_env: lint
            python-version: 3.9
          - tox_env: packaging
            python-version: 3.9
          - tox_env: py36
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.6
          - tox_env: py36-devel
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.6
          - tox_env: py37
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.7
          - tox_env: py38
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.8
          - tox_env: py39
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.9
          - tox_env: py39-devel
            PREFIX: PYTEST_REQPASS=2
            python-version: 3.9

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # needed by setuptools-scm
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # avoid https://github.com/moby/moby/issues/38185
          # sudo apt-get remove -y containerd.io docker-ce
          # sudo apt-get install -y containerd podman
          # sudo systemctl enable containerd
          podman version
          podman info
          docker version
          docker info
          python -m pip install -U pip
          pip install tox
      - name: Run tox -e ${{ matrix.tox_env }}
        run: |
          echo "${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}"
          ${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}
